# DIFF_GRM Inference Configuration
model: DIFF_GRM

# Dataset Configuration
dataset: AmazonReviews2014
category: CDs_and_Vinyl  # 可以通过命令行参数覆盖
eval_batch_size: 16      # 推理时的batch size
split: leave_one_out     # 数据集分割策略

# SID Configuration (需要与训练时一致)
n_digit: 4
codebook_size: 256
share_embeddings: true

# Model Architecture (需要与训练时一致)
encoder_n_layer: 2
decoder_n_layer: 4
n_head: 4
n_embd: 512
n_inner: 1024
dropout: 0.1
embd_pdrop: 0.1
attn_pdrop: 0.1
resid_pdrop: 0.1

# Diffusion Configuration (需要与训练时一致)
mask_probs: "1.0,0.75,0.5,0.25"    # 4种不同的掩码概率，对应4个视图
mask_prob: 0.5                     # 训练时的掩码概率（仅在未设置mask_probs时使用）
augment_factor: 4                   # 数据增强倍数（仅在未设置mask_probs时使用）
max_history_len: 50                 # 历史序列最大长度

# Sentence Embedding (for SID generation, 需要与训练时一致)
metadata: sentence
sent_emb_model: sentence-transformers/sentence-t5-base
sent_emb_dim: 768
sent_emb_pca: 128
sent_emb_batch_size: 512

# OPQ Configuration (需要与训练时一致)
opq_use_gpu: False
opq_gpu_id: 0
faiss_omp_num_threads: 32
force_regenerate_opq: true  # 推理时通常不需要重新生成OPQ结果
disable_opq: false  # 是否禁用OPQ，使用纯PQ量化

# Generation - 向量化Beam Search配置（推理专用，可调整）
vectorized_beam_search:
  beam_act: 512                    # 前3步固定beam数量，可根据显存调整
  beam_max: 512                    # 最大beam数量(不爆炸)
  top_k_final: 10                  # 最终返回的序列数量（可通过命令行覆盖）
  neg_inf_fp32: -1000000000.0      # FP32负无穷值 (-1e9)
  neg_inf_fp16: -65504.0           # FP16负无穷值

# 去重策略配置
dedup_strategy: simple           # 去重策略: none(不去重), simple(简单去重), weighted(概率加权去重)

# Evaluation Configuration (推理时使用)
topk: [5, 10]
metrics: [ndcg, recall]
val_metric: weighted_score  # 使用加权综合指标：NDCG@10 * 0.6 + RECALL@10 * 0.4

# Temperature (如果需要的话)
temperature: 0.03

# Additional configuration for inference (与训练时保持一致)
seed: 42
rand_seed: 42              # 训练时使用的随机种子字段名
reproducibility: true      # 可重现性设置

# 基础目录配置（与训练时保持一致）
cache_dir: cache/          # 数据缓存目录
log_dir: logs/             # 普通日志目录
tensorboard_log_dir: runs/  # tensorboard日志目录
ckpt_dir: ckpt/           # checkpoint目录
run_id: diff_grm_infer    # 运行ID

# 数据处理配置
num_proc: 1               # 数据处理进程数 